
/** DATA */
export const CLEAR_DATA = 'CLEAR_DATA'
export const FETCH_DATA = 'FETCH_DATA'
export const RECEIVE_DATA = 'RECEIVE_DATA'
export const KEYED_DATA = 'KEYED_DATA'

/** IDENTITY */
export const FORGET_TOKENS = 'FORGET_TOKENS'
export const FORGOTTEN_TOKENS = 'FORGOTTEN_TOKENS'
export const FORGET_FINGERPRINT = 'FORGET_FINGERPRINT'
export const FORGOTTEN_FINGERPRINT = 'FORGOTTEN_FINGERPRINT'
export const HYDRATE_TOKENS = 'HYDRATE_TOKENS'
export const PERSISTED_TOKENS = 'PERSISTED_TOKENS'
export const HYDRATE_FINGERPRINT = 'HYDRATE_FINGERPRINT'
export const PERSISTED_FINGERPRINT = 'PERSISTED_FINGERPRINT'
export const HYDRATE_IDENTITY = 'HYDRATE_IDENTITY'
export const FETCH_AUTHORIZE_IDENTITY = 'FETCH_AUTHORIZE_IDENTITY'
export const RECEIVE_AUTHORIZE_IDENTITY = 'RECEIVE_AUTHORIZE_IDENTITY'
export const FETCH_REFRESH_IDENTITY = 'FETCH_REFRESH_IDENTITY'
export const RECEIVE_REFRESH_IDENTITY = 'RECEIVE_REFRESH_IDENTITY'
export const FETCH_IMPERSONATE_IDENTITY = 'FETCH_IMPERSONATE_IDENTITY'
export const RECEIVE_IMPERSONATE_IDENTITY = 'RECEIVE_IMPERSONATE_IDENTITY'
export const FETCH_MONIKERS = 'FETCH_MONIKERS'
export const RECEIVE_MONIKERS = 'RECEIVE_MONIKERS'
export const IDENTITY_INVALID = 'IDENTITY_INVALID'
export const IDENTITY_EXPIRED = 'IDENTITY_EXPIRED'

export const FETCH_IDENTITY = 'FETCH_IDENTITY'
export const SET_IDENTITY = 'SET_IDENTITY'

/** EVENTS */
export const AUTHORIZE_MIDDLEWARE = 'AUTHORIZE_MIDDLEWARE'
export const POST_AUTHORIZE = 'POST_AUTHORIZE'
export const POST_AUTHORIZE_ADMIN = 'POST_AUTHORIZE_ADMIN'

/** CROSS CUTTING */
export const ADD_ERROR = 'ADD_ERROR'
export const DISMISS_ERROR = 'DISMISS_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

/** TIMEOUT */
export const ACTIVE_SESSION = 'ACTIVE_SESSION'
export const INACTIVE_SESSION = 'INACTIVE_SESSION'
export const EXPIRED_SESSION = 'EXPIRED_SESSION'
export const SET_SESSION_TIMEOUTS = 'SET_SESSION_TIMEOUTS'

/** SUGGESTIONS */
export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE'
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS'
export const FETCH_SUGGESTIONS = 'FETCH_SUGGESTIONS'
export const FILTER_SUGGESTIONS = 'FILTER_SUGGESTIONS'

/** VISUAL */
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY'
export const SET_VISIBILITY = 'SET_VISIBILITY'
export const SET_THEME = 'SET_THEME'
export const TOGGLE_EXPANDER = 'TOGGLE_EXPANDER'
export const SET_EXPANDER = 'SET_EXPANDER'
export const SET_TEXT = 'SET_TEXT'
export const REGISTER_TOOLTIP = 'REGISTER_TOOLTIP'
export const DISPOSE_TOOLTIP = 'DISPOSE_TOOLTIP'


/** VALIDATION */
export const SET_VALIDATED = 'SET_VALIDATED'
export const CLEAR_VALIDATED = 'CLEAR_VALIDATED'
