'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

/** DATA */
var CLEAR_DATA = exports.CLEAR_DATA = 'CLEAR_DATA';
var FETCH_DATA = exports.FETCH_DATA = 'FETCH_DATA';
var RECEIVE_DATA = exports.RECEIVE_DATA = 'RECEIVE_DATA';
var KEYED_DATA = exports.KEYED_DATA = 'KEYED_DATA';

/** IDENTITY */
var FORGET_TOKENS = exports.FORGET_TOKENS = 'FORGET_TOKENS';
var FORGOTTEN_TOKENS = exports.FORGOTTEN_TOKENS = 'FORGOTTEN_TOKENS';
var FORGET_FINGERPRINT = exports.FORGET_FINGERPRINT = 'FORGET_FINGERPRINT';
var FORGOTTEN_FINGERPRINT = exports.FORGOTTEN_FINGERPRINT = 'FORGOTTEN_FINGERPRINT';
var HYDRATE_TOKENS = exports.HYDRATE_TOKENS = 'HYDRATE_TOKENS';
var PERSISTED_TOKENS = exports.PERSISTED_TOKENS = 'PERSISTED_TOKENS';
var HYDRATE_FINGERPRINT = exports.HYDRATE_FINGERPRINT = 'HYDRATE_FINGERPRINT';
var PERSISTED_FINGERPRINT = exports.PERSISTED_FINGERPRINT = 'PERSISTED_FINGERPRINT';
var HYDRATE_IDENTITY = exports.HYDRATE_IDENTITY = 'HYDRATE_IDENTITY';
var FETCH_AUTHORIZE_IDENTITY = exports.FETCH_AUTHORIZE_IDENTITY = 'FETCH_AUTHORIZE_IDENTITY';
var RECEIVE_AUTHORIZE_IDENTITY = exports.RECEIVE_AUTHORIZE_IDENTITY = 'RECEIVE_AUTHORIZE_IDENTITY';
var FETCH_REFRESH_IDENTITY = exports.FETCH_REFRESH_IDENTITY = 'FETCH_REFRESH_IDENTITY';
var RECEIVE_REFRESH_IDENTITY = exports.RECEIVE_REFRESH_IDENTITY = 'RECEIVE_REFRESH_IDENTITY';
var FETCH_IMPERSONATE_IDENTITY = exports.FETCH_IMPERSONATE_IDENTITY = 'FETCH_IMPERSONATE_IDENTITY';
var RECEIVE_IMPERSONATE_IDENTITY = exports.RECEIVE_IMPERSONATE_IDENTITY = 'RECEIVE_IMPERSONATE_IDENTITY';
var FETCH_MONIKERS = exports.FETCH_MONIKERS = 'FETCH_MONIKERS';
var RECEIVE_MONIKERS = exports.RECEIVE_MONIKERS = 'RECEIVE_MONIKERS';
var IDENTITY_INVALID = exports.IDENTITY_INVALID = 'IDENTITY_INVALID';
var IDENTITY_EXPIRED = exports.IDENTITY_EXPIRED = 'IDENTITY_EXPIRED';

var FETCH_IDENTITY = exports.FETCH_IDENTITY = 'FETCH_IDENTITY';
var SET_IDENTITY = exports.SET_IDENTITY = 'SET_IDENTITY';

/** EVENTS */
var AUTHORIZE_MIDDLEWARE = exports.AUTHORIZE_MIDDLEWARE = 'AUTHORIZE_MIDDLEWARE';
var POST_AUTHORIZE = exports.POST_AUTHORIZE = 'POST_AUTHORIZE';
var POST_AUTHORIZE_ADMIN = exports.POST_AUTHORIZE_ADMIN = 'POST_AUTHORIZE_ADMIN';

/** CROSS CUTTING */
var ADD_ERROR = exports.ADD_ERROR = 'ADD_ERROR';
var DISMISS_ERROR = exports.DISMISS_ERROR = 'DISMISS_ERROR';
var CLEAR_ERRORS = exports.CLEAR_ERRORS = 'CLEAR_ERRORS';

/** TIMEOUT */
var ACTIVE_SESSION = exports.ACTIVE_SESSION = 'ACTIVE_SESSION';
var INACTIVE_SESSION = exports.INACTIVE_SESSION = 'INACTIVE_SESSION';
var EXPIRED_SESSION = exports.EXPIRED_SESSION = 'EXPIRED_SESSION';
var SET_SESSION_TIMEOUTS = exports.SET_SESSION_TIMEOUTS = 'SET_SESSION_TIMEOUTS';

/** SUGGESTIONS */
var UPDATE_INPUT_VALUE = exports.UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
var CLEAR_SUGGESTIONS = exports.CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
var FETCH_SUGGESTIONS = exports.FETCH_SUGGESTIONS = 'FETCH_SUGGESTIONS';
var FILTER_SUGGESTIONS = exports.FILTER_SUGGESTIONS = 'FILTER_SUGGESTIONS';

/** VISUAL */
var TOGGLE_VISIBILITY = exports.TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
var SET_VISIBILITY = exports.SET_VISIBILITY = 'SET_VISIBILITY';
var SET_THEME = exports.SET_THEME = 'SET_THEME';
var TOGGLE_EXPANDER = exports.TOGGLE_EXPANDER = 'TOGGLE_EXPANDER';
var SET_EXPANDER = exports.SET_EXPANDER = 'SET_EXPANDER';
var SET_TEXT = exports.SET_TEXT = 'SET_TEXT';
var REGISTER_TOOLTIP = exports.REGISTER_TOOLTIP = 'REGISTER_TOOLTIP';
var DISPOSE_TOOLTIP = exports.DISPOSE_TOOLTIP = 'DISPOSE_TOOLTIP';

/** VALIDATION */
var SET_VALIDATED = exports.SET_VALIDATED = 'SET_VALIDATED';
var CLEAR_VALIDATED = exports.CLEAR_VALIDATED = 'CLEAR_VALIDATED';

/** DATA */
var STREAM_DATA_START = exports.STREAM_DATA_START = 'STREAM_DATA_START';
var STREAM_DATA_META = exports.STREAM_DATA_META = 'STREAM_DATA_META';
var STREAM_DATA_RECEIVE = exports.STREAM_DATA_RECEIVE = 'STREAM_DATA_RECEIVE';
var STREAM_DATA_COMPLETE = exports.STREAM_DATA_COMPLETE = 'STREAM_DATA_COMPLETE';